# Generated by Django 4.1 on 2023-10-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapatransaction',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='created', max_length=50),
        ),
    ]
