# Generated by Django 4.1 on 2023-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chapa', '0002_chapatransaction_checkout_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapatransaction',
            name='event',
        ),
    ]
