# Generated by Django 4.1 on 2023-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chapa', '0003_remove_chapatransaction_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapatransaction',
            name='payment_title',
            field=models.CharField(default='Payment', max_length=255),
        ),
    ]
